import "/Users/lakshmikrishnan/Desktop/latest/src/style/About.css"
import NavBar from "../navigate/NavBar";
export default function About(){
  return<> <div className = 'nav-app'><NavBar/></div>
  <img src = "https://media.licdn.com/dms/image/D5603AQFVvl6sjjb4dA/profile-displayphoto-shrink_800_800/0/1675707827884?e=1708560000&v=beta&t=gKJRVqbSHaycBX_D3jcbnMAsacoUkU1uSKyJxpcures"/>
  <h1 className = "header-passage">Hi! I'm a junior at University of Illinois at Chicago, majoring in Computer Science. When I was little, I initially embarked on a journey as a pre-med enthusiast, deeply committed to the field of medicine. However, a pivotal moment occurred when a class project, initially a simple academic endeavor, evolved into a community service initiative. This transformation marked the birth of my passion for computer science. It was during this process that I discovered my knack for debugging and resurrecting malfunctioning code, persistently working until it achieved a state of perfection. This experience solidified my dedication to the world of computer science, and I've since evolved into a passionate programmer. I proudly earned the 2nd Best Project award at the UIC Spark Hacks Hackathon for co-creating a Social Networking App. My proficiency extends across multiple programming languages, including C++, Python, and Java, and I've delved into web development with HTML, CSS, and JavaScript. My diverse experiences, including a role as a Research Assistant at UIC College of Engineering and a Web Development Internship at Tech Citi in Bangalore, have honed my skills in areas like NLI models, HTML, CSS, and audio/video integration. I find joy in crafting interactive experiences, exemplified by my work on projects like the Multiplayer Poker Game, and have a deep passion for creating secure and user-friendly applications, as evident in my contributions to the Social Networking App. </h1>
  <p className="yada">In the intricate tapestry of our lives, one fundamental thread weaves through every interaction, decision, and emotion—our understanding of people psychology. It is the silent force that shapes our perceptions, guides our relationships, and influences our collective journey as a society. As someone deeply passionate about unraveling the complexities of the human mind, I am driven by a fervent desire to spread awareness about the profound impact that psychology has on our daily lives.

Every smile, every tear, and every decision made by an individual is a manifestation of their unique psychological makeup. Yet, amidst the hustle and bustle of our modern world, the significance of mental well-being often takes a back seat. I believe that fostering a deeper awareness of people psychology is not just a necessity but a responsibility—one that has the power to transform lives and build a more compassionate, understanding community.

As I embark on this journey to shed light on the intricacies of the human mind, my mission is clear: to spark conversations, challenge misconceptions, and create a platform where the richness of our psychological experiences can be shared and understood. Whether it's exploring the impact of emotions on decision-making or navigating the nuances of interpersonal relationships, the realm of psychology is vast, and its lessons are invaluable.

Join me on this exploration into the heart of human psychology, where the complexities are embraced, and the power of understanding becomes a catalyst for positive change. Together, let's peel back the layers, destigmatize mental health conversations, and cultivate a society that values the well-being of each unique mind within it.

</p>
  </>
}